---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары	
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Нужно разработать интерфейс интернет-магазина с просмотром и фильтрацией товаров, а также добавлением их в корзину
  - Пользователь будет просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом
  - На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее
  - Пользователь будет добавлять товар в корзину и продолжать выбирать товары в каталоге
  - На странице корзины пользователь cможет удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты
  
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Ключевой возможностью магазина будет адаптивная верстка, чтобы он был удобным на мобильных устройствах
  - Также магазин будет SPA-приложение, которое не перезагружает страницу
  - Корзина будет хранится в сессии браузера
  
implicit:
  - При добавлении товара в корзину у пользователя должна быть возможность выбрать нужное колличество
  - У пользователя должна быть возможность удалять товар из корзины
  - При заказе товара у пользователя должен быть выбор оплаты
  - У сайта должно быть 2 языка интерфейса Русский и Английский
  - Пользователь не может редактировать описание товара
